## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1. Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [13]:
import numpy as np
np.linspace(-1.3,2.5,64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2. Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [14]:
import numpy as np
def circle(n):
    a = np.array([1, 2, 3]*3*n)
    return a
print(circle(5))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1
 2 3 1 2 3 1 2 3]


3. Создайте массив первых 10 нечетных целых чисел.

In [3]:
import numpy as np
def odd(n):
    b = np.arange(1, 2*n, 2)
    return b
print(odd(10))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [5]:
def matrix(n):
    matrix = np.zeros((n,n))
    matrix[0] = 1
    matrix[n-1] = 1
    matrix[:, 0] = 1
    matrix[:, n-1] = 1
    return matrix
print(matrix(10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [6]:
def chess_matrix(n):
    matrix = np.zeros((n,n))
    matrix[0::2, 0::2] = 1
    matrix[1::2, 1::2] = 1
    return matrix
print(chess_matrix(8))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [34]:
import numpy as np
def matrix(n):
    rows_index = np.arange(n)
    cols_index = np.arange(n)
    return rows_index[:, np.newaxis] + cols_index
print(matrix(7))

[[ 0  1  2  3  4  5  6]
 [ 1  2  3  4  5  6  7]
 [ 2  3  4  5  6  7  8]
 [ 3  4  5  6  7  8  9]
 [ 4  5  6  7  8  9 10]
 [ 5  6  7  8  9 10 11]
 [ 6  7  8  9 10 11 12]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [31]:
import numpy as np
vector1 = np.random.randint(5, size = 4)
vector2 = np.random.randint(5, size = 4)
matrix1 = np.random.randint(5, size = (3,4))
matrix2 = np.random.randint(5, size = (4,3))

vectors_multiplication = np.dot(vector1, vector2)
matrix_vector_multiplication = np.dot(matrix1, vector1)
matrixes_multiplication = np.dot(matrix1, matrix2)

print(vectors_multiplication)
print(matrix_vector_multiplication)
print(matrixes_multiplication)


21
[14 15 17]
[[ 5 12  9]
 [ 9  4 14]
 [ 5 16 11]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [32]:
import numpy as np
xx = np.arange(0, 1.05, 0.05)
cos = np.cos(xx * np.pi)
sin = np.sin(xx * np.pi)
result = np.vstack((cos, sin))
print(result)

[[ 1.00000000e+00  9.87688341e-01  9.51056516e-01  8.91006524e-01
   8.09016994e-01  7.07106781e-01  5.87785252e-01  4.53990500e-01
   3.09016994e-01  1.56434465e-01  6.12323400e-17 -1.56434465e-01
  -3.09016994e-01 -4.53990500e-01 -5.87785252e-01 -7.07106781e-01
  -8.09016994e-01 -8.91006524e-01 -9.51056516e-01 -9.87688341e-01
  -1.00000000e+00]
 [ 0.00000000e+00  1.56434465e-01  3.09016994e-01  4.53990500e-01
   5.87785252e-01  7.07106781e-01  8.09016994e-01  8.91006524e-01
   9.51056516e-01  9.87688341e-01  1.00000000e+00  9.87688341e-01
   9.51056516e-01  8.91006524e-01  8.09016994e-01  7.07106781e-01
   5.87785252e-01  4.53990500e-01  3.09016994e-01  1.56434465e-01
   1.22464680e-16]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [33]:
import numpy as np
A = np.random.rand(3, 5) * 4 - 1
print(A)

[[ 1.46795799  1.51105177  2.2730016   1.43165902 -0.64078137]
 [ 1.88575679  0.50668558  2.76194902  1.08906431 -0.71037114]
 [-0.98548252  0.76036513  1.45757896  2.36778759  0.7002152 ]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [36]:
import numpy as np
sum_elements = np.sum(A)
sum_rows = np.sum(A, axis = 1)
sum_cols = np.sum(A, axis = 0)
mean_rows = np.mean(A, axis = 1)
var_rows = np.var(A, axis = 1)
std_rows = np.std(A, axis = 1)
print(sum_elements)
print(sum_rows)
print(sum_cols)
print(mean_rows)
print(var_rows)
print(std_rows)

15.876437925510483
[6.04288901 5.53308456 4.30046436]
[ 2.36823226  2.77810248  6.49252959  4.88851091 -0.65093731]
[1.2085778  1.10661691 0.86009287]
[0.95233224 1.40177092 1.2143576 ]
[0.97587512 1.18396407 1.10197895]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [37]:
import numpy as np
A = (A - mean_rows[:, np.newaxis]) / std_rows[:, np.newaxis]
print(A)

[[ 0.2657924   0.30995151  1.09073772  0.22859607 -1.89507771]
 [ 0.6580773  -0.50671413  1.39812697 -0.01482529 -1.53466486]
 [-1.6747828  -0.09049878  0.54219374  1.36817016 -0.14508233]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [38]:
import numpy as np
sort_index = np.argsort(A[:, 2])
A_sorted = A[sort_index]
print(A_sorted)

[[-1.6747828  -0.09049878  0.54219374  1.36817016 -0.14508233]
 [ 0.2657924   0.30995151  1.09073772  0.22859607 -1.89507771]
 [ 0.6580773  -0.50671413  1.39812697 -0.01482529 -1.53466486]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [44]:
import numpy as np
B = np.dot(A.T, A)
C = np.dot(A, A.T)
print('B = ', B)
print('C = ', C)

B =  [[ 3.30860878 -0.09950852  0.30192866 -2.24038495 -1.27064397]
 [-0.09950852  0.36101918 -0.41944276 -0.04545184  0.20338395]
 [ 0.30192866 -0.41944276  3.43844188  0.97042403 -4.29135181]
 [-2.24038495 -0.04545184  0.97042403  1.92436555 -0.60895278]
 [-1.27064397  0.20338395 -4.29135181 -0.60895278  5.96756462]]
C =  [[ 5.          4.44776512  0.70589701]
 [ 4.44776512  5.         -0.09585461]
 [ 0.70589701 -0.09585461  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [45]:
import numpy as np
sum_B = np.trace(B)
sum_C = np.trace(C)
print(sum_B)
print(sum_C)

15.0
15.0


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [ ]:
import numpy as np
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_C = np.linalg.matrix_rank(C)
eigvalsh_B = np.linalg.eigvalsh(B)
eigvalsh_C = np.linalg.eigvalsh(C)
print(det_B)
print(det_C)
print(ran)

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [3]:
import numpy as np
np.random.seed(1032204229)
np.random.randint(9)

6

In [5]:
def f(x):
    return (np.cosh(3*x))**2

def integral(f, a, b, dx):
    N = int((b-a) / dx) 
    xk = np.linspace(a, b, N) 
    rectan = dx*np.sum(f(xk))  
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"


anal_solution = np.float64(0.468905)  
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [0; 1/3]")

for i in range(6):
    print(integral(f, 0, np.float64(1/3), 0.1 * 0.1**i))

0.468905 - аналитическое решение функции f(x) на отрезке [0; 1/3]
0.4652638162949438, 0.30084555447390965, 0.11579434848876498 при шаге интегрирования 0.1
0.4671487651967749, 0.45024777731922777, 0.41986705984499606 при шаге интегрирования 0.010000000000000002
0.468720873130051, 0.4670303287072936, 0.46386914000883667 при шаге интегрирования 0.0010000000000000002
0.46888653593671314, 0.4687174810489361, 0.4684001373512136 при шаге интегрирования 0.00010000000000000003
0.468903183365795, 0.46888627787657183, 0.4688545312653783 при шаге интегрирования 1.0000000000000003e-05
0.4689048489169453, 0.4689031583680226, 0.4688999835844958 при шаге интегрирования 1.0000000000000004e-06
